# Generated by Django 3.2.4 on 2021-07-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20210707_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Organisation',
        ),
    ]
