# Generated by Django 3.2.4 on 2021-07-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_rename_userprofile_organisation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organisation',
            new_name='UserProfile',
        ),
    ]
